name: Build Code and Publish Artifacts

on:
  workflow_call:
    inputs:
      gh_runner:
        required: true
        type: string
      dotnet_version:
        description: ".NET SDK version (if runtime is dotnet)"
        required: true
        type: string
      solution_file:
        description: "solution file"
        required: true
        type: string    
      build_location:
        required: true
        type: string
      build_location_name:
        required: true
        type: string
      unit_tests_available:
        description : "unit tests available"   
        required: false
        type: boolean    
        default: true     
      integration_tests_available:
        description : "integration tests available"   
        required: false
        type: boolean    
        default: true   
                      
    outputs:
      gh_runner:
        value: ${{ inputs.gh_runner }}
      dotnet_version:
        value: ${{ inputs.dotnet_version }}
      solution_file:
        value: ${{ inputs.solution_file }}

jobs:
  build:
    runs-on:
      group: ${{ inputs.gh_runner }}
    outputs:
      dotnet_version: ${{ inputs.dotnet_version }}
      solution_file: ${{ inputs.solution_file }}
      gh_runner: ${{ inputs.gh_runner }}
    strategy:
      matrix:
        language: [ 'csharp' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet_version: ${{ inputs.dotnet_version }}

      - name: .NET Restore
        run: dotnet restore ${{ inputs.solution_file }}

      - name: .NET Build
        run: dotnet build ${{ inputs.solution_file }} --no-restore --configuration Release

      - name: .NET Unit Tests
        if: ${{ inputs.unit_tests_available }}
        run: |
          for test_project in $(find . -name '*.Tests.csproj'); do
          echo "Running tests for $test_project"
          dotnet test "$test_project" --no-build --configuration Release --verbosity normal
          done
    
      - name: .NET Integration Tests
        if: ${{ inputs.integration_tests_available }}
        run: |
          for test_project in $(find . -name '*.IntegrationTests.csproj'); do
          echo "Running tests for $test_project"
          dotnet test "$test_project" --no-build --configuration Release --verbosity normal
          done

      #- name: Initialize CodeQL
      #  uses: github/codeql-action/init@v3
      #  with:
      #    language: ${{ matrix.language }}
      #
      #- name: Perform CodeQL Analysis
      #  uses: github/codeql-action/analyze@v3
      #

      - name: .NET Publish
        run: |
          for project in $(find . -name '*.csproj' -not -name '*Tests.csproj'); do
          echo "Publishing $project"
          dotnet publish "$project" --configuration Release --output ./publish
          done

      - name: Upload .NET Publish Output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_location_name }}
          path: ${{ inputs.build_location }}   
        
    

     
