name: Build Frontend, Publish Artifacts, and Build Docker Image

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      build_location:
        required: true
        type: string
      build_location_name:
        required: true
        type: string
      gh_runner:
        required: true
        type: string
      unit_tests_available:
        description : "unit tests available"   
        required: true
        type: boolean    

jobs:
  angular:
    name: Angular Build
    runs-on:
      group: ${{ inputs.gh_runner }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node_version: ${{ inputs.node_version }}

      - name: Clear npm cache
        run: npm cache clean --force      

      - name: Authenticate with GitHub Packages
        run: |
          echo "@BAG-DT:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          cat ~/.npmrc 
        
      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli  

      - name: Lint Angular App
        run: npm run lint

      - name: Test Angular App
        if: ${{ inputs.unit_tests_available }}
        run: npm run test -- --configuration production

      - name: Build Angular App
        run: npm run build -- --output-path=${{ inputs.build_location }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_location_name }}
          path: ${{ inputs.build_location }}

      - name: Debug npm config
        run: npm config list    
