name: Build Frontend, Publish Artifacts, and Build Docker Image

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      package-manager:
        required: true
        type: string
        default: npm
      build-location:
        required: true
        type: string
      gh_runner:
        required: false
        type: string
        default: "ubuntu-latest"s

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force      

      - name: Authenticate with GitHub Packages
        run: |
          echo "@BAG-DT:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          cat ~/.npmrc 
        
      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli  

      - name: Build Angular App
        run: npm run build -- --output-path=${{ inputs.build-location }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ${{ inputs.build-location }}

      - name: Debug npm config
        run: npm config list    
