name: Reusable CI/CD Pipeline dotnet

on:
  workflow_call:
    inputs:
      gh_runner:
        required: true
        type: string
        default: 'ubuntu-latest'  
      runtime:
        required: true
        type: string
        default: 'dotnet'
      solution_file:
        required: true
        type: string
      dotnet_version: 
        required: true
        type: string
        default: "8.0.x"
      reg_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      containerAppName: 
        required: true
        type: string 
      build_location:
        required: true
        type: string
      build_location_name:
        required: true
        type: string
      changelog_file:
        required: true
        type: string
        default: 'CHANGELOG.md'
      files_pattern:
        required: true
        type: string
        default: 'src/**'
      ignored_files:
        required: true
        type: string
        default: 'src/test/** docs/**".gitignore'
      report_format:
        required: true
        type: string
        default: 'HTML' 
      release_Features:
        description: "release Features"
        required: false
        type: string      
      bugfixes:
        description: "release Features"
        required: false
        type: string      
      release_refactoring:
        description: "release Refactoring"
        required: false
        type: string      
      sonar_project_name:
        description: "sonar project name"
        required: false
        type: string
        default: true 
      owasp_scan_path: 
        description: 'owasp scan path'
        required: false
        type: string
        default: 'src'   
        
    secrets:
      AZURE_CREDENTIALS:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      SONAR_PROJECT_KEY:   
        required: true     
      GH_PAT:
        required: true           

jobs:
  build:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/build-dotnet.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      dotnet_version: ${{ inputs.dotnet_version }} 
      solution_file: ${{ inputs.solution_file }}
      build_location: ${{ inputs.build_location }}
      build_location_name: ${{ inputs.build_location_name }} 

  static-code-analysis-dotnet:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/static-code-analysis-dotnet.yml@main
    with:
      dotnet_version: ${{ inputs.dotnet_version }}
      sonar_project_name: ${{ inputs.solution_file }}  
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
      SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}
  
  owasp-scan:    
    uses: bag-hpp/Bag.Pipelines/.github/workflows/owasp.yml@main    
    with:
      project_path: ${{ inputs.owasp_scan_path }}
      report_format: ${{ inputs.report_format }}

  #codeql:
  #  needs: [build]
  #  uses: bag-hpp/Bag.Pipelines/.github/workflows/codeql-dotnet.yml@main    
  #  with:
  #    build_location: ${{ inputs.build_location }}
  #    build_location_name: ${{ inputs.build_location_name }}

  build-docker:
    needs: [build, owasp-scan, static-code-analysis-dotnet]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/docker-build-and-push.yml@main
    with:
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      runtime: ${{ inputs.runtime }}
      build_location: ${{ inputs.build_location }}
      build_location_name: ${{ inputs.build_location_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}   

  deploy-github:
    needs: [build-docker]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/deploy-with-github.yml@main
    with:
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      resource_group: ${{ inputs.resource_group }}
      containerAppName: ${{ inputs.containerAppName }} 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}              

  release:
    needs: [build-docker]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/release.yml@main
    with:
      release_Features: ${{ inputs.release_Features }}
      bugfixes: ${{ inputs.bugfixes }}
      release_refactoring: ${{ inputs.release_refactoring }}    

  publish-changelog:
    needs: [build-docker]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changelog.yml@main
    with:
      changelog_file: ${{ inputs.changelog_file }}

  changed-files:
    needs: [build-docker]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changed-files.yml@main
    with:
      files_pattern: ${{ inputs.files_pattern }}
      ignored_files: ${{ inputs.ignored_files }}   