name: Reusable CI/CD Pipeline Angular

on:
  workflow_call:
    inputs:
      gh_runner:
        required: true
        type: string
        default: 'ubuntu-latest'
      runtime:
        required: false
        type: string
        default: 'angular'
      reg_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      containerAppName: 
        required: true
        type: string 
      files_pattern:
        required: true
        type: string
        default: 'src/**'
      ignored_files:
        required: true
        type: string
        default: 'node_modules/** .gitignore'
      report_format:
        required: true
        type: string
        default: 'HTML'
      release_Features:
        description: "release Features"
        required: false
        type: string 
      bugfixes:
        description: "release Features"
        required: false
        type: string   
      release_refactoring:
        description: "release Refactoring"
        required: false
        type: string    
      node_version:
        description: 'Node.js version to use'
        required: true
        type: string
      package_manager:
        description: 'Package manager (npm, yarn, pnpm)'
        required: true
        type: string
        default: npm    
      build_location:   
        description: "FE build location"
        required: false
        type: string      
      changelog_file:
        required: true
        type: string
        default: 'CHANGELOG.md'
      sonar_available:
        required: true
        type: boolean
        default: true
      sonar_project_name:  
        required: true
        type: string    
      owasp_available: 
        description: 'owasp scan available'
        required: false
        type: boolean
        default: false   
      owasp_scan_path: 
        description: 'owasp scan path'
        required: false
        type: string
        default: 'src'  
      publish_changelog_available:
        description: 'publish changelog available'
        required: false
        type: boolean
        default: false   
      changed_files_available:
        description: 'changed files available'
        required: false
        type: string
        default: false 
      build_docker_available:
        description: 'build docker available'
        required: false
        type: boolean
        default: false 
      deploy_github_available:
        description: 'deploy with github available'
        required: false
        type: boolean
        default: false 
      release_available:
        description: 'release available'
        required: true
        type: boolean
        default: false

    secrets:
      AZURE_CREDENTIALS:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      SONAR_PROJECT_KEY:   
        required: true     
      GH_PAT:
        required: true      

jobs:
  build:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/build-angular.yml@main
    with:
      node-version:  ${{ inputs.node_version }}
      package-manager:  ${{ inputs.package_manager }}
      build-location:  ${{ inputs.build_location }}
    secrets:
      AZURE_STATIC_WEBS_APP_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEBS_APP_DEPLOYMENT_TOKEN }}      

  owasp-scan:
    if: ${{ inputs.owasp_available }}
    needs: [build]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/owasp.yml@main    
    with:
      project_path: ${{ inputs.owasp_scan_path }}
      report_format: ${{ inputs.report_format }}     

  build-docker:
    if: ${{ inputs.build_docker_available }}
    needs: [build]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/docker-build-and-push.yml@main
    with:
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      runtime: ${{ inputs.runtime }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}   

  deploy-github:
    if: ${{ inputs.deploy_github_available }}
    needs: [build]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/deploy-with-github.yml@main
    with:
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      resource_group: ${{ inputs.resource_group }}
      containerAppName: ${{ inputs.containerAppName }} 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}                            

  release:
    if: ${{ inputs.release_available  }}
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/release.yml@main
    with:
      release_Features: ${{ inputs.release_Features }}
      bugfixes: ${{ inputs.bugfixes }}
      release_refactoring: ${{ inputs.release_refactoring }}   

  publish-changelog:
    if: ${{ inputs.publish_changelog_available }}
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changelog.yml@main
    with:
      changelog_file: ${{ inputs.changelog_file }}

  changed-files:
    if: ${{ inputs.changed_files_available }}
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changed-files.yml@main
    with:
      files_pattern: ${{ inputs.files_pattern }}
      ignored_files: ${{ inputs.ignored_files }}     
