name: Reusable CI/CD Pipeline Angular

on:
  workflow_call:
    inputs:
      gh_runner:
        required: true
        type: string
      runtime:
        required: true
        type: string
        default: 'angular'
      build_location:
        required: true
        type: string
      build_location_name:
        required: true
        type: string
      reg_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      containerAppName: 
        required: true
        type: string 
      files_pattern:
        required: true
        type: string
        default: 'src/**'
      ignored_files:
        required: true
        type: string
        default: 'node_modules/** .gitignore'
      report_format:
        required: true
        type: string
        default: 'HTML'
      release_Features:
        description: "release Features"
        required: false
        type: string 
      bugfixes:
        description: "release Features"
        required: false
        type: string   
      release_refactoring:
        description: "release Refactoring"
        required: false
        type: string    
      node_version:
        description: 'Node.js version to use'
        required: true
        type: string    
      changelog_file:
        required: true
        type: string
        default: 'CHANGELOG.md'
      sonar_project_name:  
        required: true
        type: string    
      owasp_scan_path: 
        description: 'owasp scan path'
        required: false
        type: string
        default: 'src'  

    secrets:
      AZURE_CREDENTIALS:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      SONAR_PROJECT_KEY:   
        required: true     
      GH_PAT:
        required: true      

jobs:
  build:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/build-angular.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      node_version:  ${{ inputs.node_version }}
      build_location:  ${{ inputs.build_location }}   
      build_location_name:  ${{ inputs.build_location_name }}  

  static-code-analysis-angular:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/static-code-analysis-angular.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      node_version: ${{ inputs.node_version }}  
    secrets:      
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
      SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}

  owasp-scan:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/owasp.yml@main    
    with:
      gh_runner: ${{ inputs.gh_runner }}
      project_path: ${{ inputs.owasp_scan_path }}
      report_format: ${{ inputs.report_format }}     
  
  #codeql:
  #  needs: [build]
  #  uses: bag-hpp/Bag.Pipelines/.github/workflows/codeql-angular.yml@main    
  #  with:
  #    node_version:  ${{ inputs.node_version }}
  #    build_location: ${{ inputs.build_location }}
  #    build_location_name: ${{ inputs.build_location_name }}

  build-docker:
    needs: [build, owasp-scan ] #, static-code-analysis-angular, codeql]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/docker-build-and-push.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      runtime: ${{ inputs.runtime }}
      build_location: ${{ inputs.build_location }}
      build_location_name: ${{ inputs.build_location_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}   

  deploy-github:
    needs: [build-docker]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/deploy-with-github.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      registry: ${{ inputs.reg_name }}
      app_name: ${{ inputs.app_name }}
      resource_group: ${{ inputs.resource_group }}
      containerAppName: ${{ inputs.containerAppName }} 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}                            

  release:
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/release.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      release_Features: ${{ inputs.release_Features }}
      bugfixes: ${{ inputs.bugfixes }}
      release_refactoring: ${{ inputs.release_refactoring }}   

  publish-changelog:
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changelog.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      changelog_file: ${{ inputs.changelog_file }}

  changed-files:
    needs: [deploy-github]
    uses: bag-hpp/Bag.Pipelines/.github/workflows/changed-files.yml@main
    with:
      gh_runner: ${{ inputs.gh_runner }}
      files_pattern: ${{ inputs.files_pattern }}
      ignored_files: ${{ inputs.ignored_files }}     
