name: Feature Pipeline java

on:
  push:
    branches-ignore: [ "main" ] 
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  actions: read
  packages: write
  id-token: write
  security-events: write

jobs:
  pipeline-feature-java:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/buld/buld-java.yml@main
    with:
      gh_runner: 'ubuntu-latest'
      runtime: 'java'
      distribution: 'temurin'
      build_location: './publish' 
      build_location_name: 'dotnet-app'
