name: Dev Pipeline java

on:
  push:
    branches: [ "main" ] 

permissions:
  contents: write
  actions: read
  packages: write
  id-token: write
  security-events: write

jobs:
  pipeline-feature-java:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/cicd/cicd-java.yml@main
    with:
      gh_runner: 'ubuntu-latest'
      runtime: 'java'
      distribution: 'temurin'
      reg_name: '' #bagcrmgmacrcorchn0
      app_name: '' #edi-bag-cr/ncds/fe
      resource_group: '' #bag-rg-cr-dev-chn-0
      containerAppName: '' #bag-ca-cr-ncds-fe-dev-chn-0
      build_location: './target/*.jar' 
      build_location_name: 'app-jar'
      changelog_file: 'CHANGELOG.md'
      files_pattern: "src/**"
      ignored_files: 'node_modules/** .gitignore'
      report_format: 'HTML'
      release_Features: ''
      bugfixes: ''
      release_refactoring: ''
      sonar_available: false
      sonar_project_name: ''
      owasp_available: false
      owasp_scan_path: 'src'       
      publish_changelog_available: false
      changed_files_available: false
      build_docker_available: true     
      deploy_github_available: true
      release_available: false
      static_code_analysis_available: false
      codeql_available: false
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      GH_PAT: ${{ secrets.PAT_TOKEN }}
