name: Feature Pipeline Angular

on:
  push:
    branches-ignore: [ "main" ] 
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  actions: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build-angular:
    uses: bag-hpp/Bag.Pipelines/.github/workflows/build/build-angular.yml@main
    with:
      gh_runner: 'ubuntu-latest'
      node_version: '20.18.0'
      build_location: 'dist/browser'  
      build_location_name: 'frontend-build'
