name: Static Code Analysis angular

on:
  workflow_call:
    inputs:
      gh_runner:
        required: true
        type:     string   
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_PROJECT_KEY:
        required: true
        
jobs:
  static-code-analysis:
    runs-on:
      group: ${{ inputs.gh_runner }}
    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0 
     - uses: SonarSource/sonarqube-scan-action@v5
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}